FIREBASE_API_KEY="AIzaSyCluIq18pi3-Jh196MYT29UtNuongtIGjc"
COOKIE_KEY="streamlit_i7sgtf6segflihwGkWL134e3hb14312"
REDIRECT_URI_GOOGLE="https://vendor-fuzz-match.onrender.com/"
STREAMLIT_RUNTIME_ENV="cloud"
google_credentials = '''
{
  "web": {
    "client_id": "284238408395-02i73coe7cu1bjipihevnt88hbet69a5.apps.googleusercontent.com",
    "project_id": "exp-pro-fadfc",
    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
    "token_uri": "https://oauth2.googleapis.com/token",
    "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
    "client_secret": "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",
    "javascript_origins": ["http://localhost:8501", "https://vendor.mpamanagement.com"]
  }
}
'''


[firebase_auth_token]
type = "service_account"
project_id = "exp-pro-fadfc"
private_key = "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDVkcPupeAslQuy\nLL2As0deLIHdctfD7vQq5k+0jILZMBbX3PtixL9qWmRw5X03htY+REe131Gtwzk1\n6CYkmVvEuqt6HG39ZnRri28BvmOLxFBgg8zg8IvvNtP+NU6GzzF0l4ru2zO7/mjV\nUZarLrdfbjLhpty5s6ueUoNJAaCpc6KVVxRGpnIPmfhgX7sEnNIx3mJgg4OLSfXu\nDX99VeACnIn7NumqZRnih8770I/Mqnn3K5YRBPcqyuKa81K4YHSsCzkUd23b7Nzy\nCtNROOtemLxvMnUx+2F3hlNDQWZiY13t+eLM4uv1LF+kostsAkP3QRjzrq94WLsi\n3H1vQW2/AgMBAAECggEALfg+ts8ghigcyODFd37fZT9qQprWI5f7GYLSdDfscEhg\nGl24BIX596/2P7C996Y/1k5HKzgi8iZ72YUbNLSH4rwVbebRrAISHBX6smLjNXHv\npR6pil9sl3RzRBwAR5cwe3qlDo3DQHtd4FC8ACPBl7p2HEkY6KXqUl1LYfsGNILJ\nOhMUj7VB6PSvm7ZLDJ0PLwvp70cHTKpN4LDw9ux0LQJHTzDWT9xvoCAFG1uwv6J+\ntw1TsccelgKCG6F2uxnLAk18qeHvUxjSfCwwv1qHLCPx0X3x5iizPbuDG7bvfhgz\nLflkjLqshToWemtEBcXA0TjoglmIINW60UR5seImfQKBgQDrQehzNuF66v90Fw3c\nileuilEdV8WbKBCXIKRF+IF7y2h+4j5hrDoEGMDh2epW2w8PNZH5zRAXvTJP3Rmv\n6vdSWTe0M4K4o5A2ForvTljyR28hfSuXk2rPJBDXzwkxC9/ummWAMWHlYwrpWdfH\n/p8YQiwX/SXWZ9NIovQw6argCwKBgQDoZlPN738/v3cEzQmOESgm7aCUQRmdlqcX\nHoQnKjqbOx+/nObUAC/wmj7lcvf1uAwgNG25knCBlY4wy9A/Pj5LZidRBi8cxShr\n3AXNwJg5yvxPN2Q4IQR0jlWb1+wJ8kMh+l1J1725nhHlkH5ncoueyDlG2FFl64ej\n7xVxINN1nQKBgQDe29GbCzswWNtjms9Lw1XqhybuGA6eu6Zzs71Kd24Z2ogD4sjb\nd+6BoP1fNjLS0rOCYeoF7Kc5BcZad4X06y4dOV0WfNFxnahoRJSau+pwoRD6dXvN\nHB5LWcwG1B7N8oTQoDxU4vLs/RUCF1TdJSyLK2xf0TR91l8FaTDQARsZHwKBgH7g\n/vf7vXlMSupwFrtdWpKGQZkvQZDr4yWYH4ZSY9TEHr06KDuuLn4peBVFA2M/rD8Y\n4J7j+FCHGi5B19vvW4tGpkhyG96VNVBNu01tzK4gyEdncmvCevA3lT2UUOXNQiGW\n0r+x7X8dcZ/nl1tbCicSIVMwXqBKSq+RpB8zUL9xAoGBALE9p4B4M+b538y1OYBG\njYADjuUdyjrS9OUtnsecrd6q5DhKcXOmGw/lWhn+Unepa4f/DHEB0o+WH43Mw+Ie\nG/KPj262SBQK2mpI1asTr8rIg4wKt+hJDHSl2J8vkUmNJWlcUrKUB6LqzfQlzEUQ\n8K76XegQAbZXCgFMtwDq+KAs\n-----END PRIVATE KEY-----\n"
private_key_id = "61f171e2acade9de810008f3ebac507bc4b78605"
client_email = "firebase-adminsdk-fbsvc@exp-pro-fadfc.iam.gserviceaccount.com"
client_id = "109366298203655370955"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
